- name: Build custom build container
        run: docker build -t nickeltc-qt5 .

      - name: Build NickelHook Plugin
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            -w /workspace \
            nickeltc-qt5 \
            bash -c "make clean && make koboroot"
