name: Build NickelHook Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker Image
        run: docker build -t nickeltc-qt5 .

      - name: Build NickelHook Plugin inside Container
        run: |
          docker run --rm \
            --user root \
            -v $(pwd):/workspace \
            -w /workspace \
            nickeltc-qt5 \
            bash -c "make clean && make koboroot"

      - name: Upload KoboRoot Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KoboRoot
          path: KoboRoot.tgz
